version: "3.9"

networks:
  course-network:
    driver: bridge

services:
  course-mongodb:
    image: mongo
    container_name: "course-mongodb"
    ports:
      - "27017:27017"
      - "23456:28017"
    environment:
      MONGODB_APPLICATION_DATABASE: learning_course
    networks:
      - course-network

  course-api:
    image: course-api
    #command: ["/wait-for-it.sh", "course-mongodb:27017", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
       - MONGODB_URI=mongodb://course-mongodb:27017/learning_course
       - MONGODB_STATUS_HOST=course-mongodb
       - MONGODB_STATUS_PORT=28017
    ports:
      - "8081:8081"
    networks:
      - course-network
    depends_on:
      - course-mongodb