spring:
  application:
    name: course
  data:
    mongodb:
      database: learning_course
      port: 27017
      host: {localhost:course-mongodb}
      repositories:
        enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8081

