spring:
  application:
    name: student
  data:
    mongodb:
      database: learning_cad
      port: 27017
      host: {localhost:student-mongodb}
      repositories:
        enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  kafka:
    bootstrap-servers: localhost:29092

server:
  port: 8082